### ISSUE TITLE
Example for collections seems broken

### ISSUE THREAD

**Issue by mmalecki** [Marak/HTML#6]
On commit 1a9ed3336501ce34b4512d54763bdd93018b9d98, I get this:

```
[maciej@pc09 HTML (master)]$ node examples/collection/collection.js
<div class="users">            <div class="user">              <p class="name">name placeholder</p>              <p class="email">email placeholder</p></div>          </div>
```

Seems like collections/collections example is broken.

**Comment by Marak** [comment]
Looks like the latest version of cheerio was causing it to break. 

https://github.com/Marak/HTML/commit/90842931206f53062f2953cd75e20e7ab8c88fff seems to fix.
