### ISSUE TITLE
Using cheerio is slow

### ISSUE THREAD

**Issue by pksunkara** [Marak/HTML#9]
What are the alternatives?

**Comment by Marak** [comment]
Slow is a relative term. Please provide objective evidence in how cheerio is slow. Providing benchmarks of performance would seem appropriate.

Until you have provided proof your claim is unsubstantiated.

**Comment by pksunkara** [comment]
This lib needs only a subset of cheerio especially the DOM model can be excluded. Directly using htmlparser would be faster atleast in theory.

**Comment by Marak** [comment]
If you have a theory, you can use the [scientific method](https://en.wikipedia.org/wiki/Scientific_method) to test it.

I look forward to seeing what information you can discover.
